trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs: 
  - job: mytest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az feedback'